version: '3.9'

services:
  backend:
    container_name: deselflopment-babl-backend
    build:
      context: backend
      dockerfile: Dockerfile
    command: ["air", "migrate", "&&", "air", "serve"]
    env_file:
      - backend/.env
    ports:
      - "11007:11007"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: deselflopment-babl-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    command: ["npm", "run", "start:prod"]
    env_file:
      - frontend/.prod.env
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./backend:/deselflopment-babl/frontend
