version: '3.9'

services:
  backend:
    container_name: deselflopment-babl-backend
    build:
      context: backend
      dockerfile: Dockerfile
    command: ["air", "automigrate", "&&", "air", "serve"]
    env_file:
      - backend/.env
    ports:
      - "18009:18009"
    networks:
      deselflopment-database-network: { }
      deselflopment-webserver-network: { }
    volumes:
      - ./backend:/deselflopment-babl/backend

networks:
  deselflopment-database-network:
    external: true
  deselflopment-webserver-network:
    external: true
